/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.GiaoDichDAO;
import dao.KhachHangDAO;
import dao.XeDAO;
import dto.GiaoDichDTO;
import dto.XeDTO;
import java.sql.Date;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import dto.KhachHangDTO;
import java.awt.Toolkit;
/**
 *
 * @author Admin
 */
public class FrmGiaodich extends javax.swing.JFrame {
    ArrayList<GiaoDichDTO> listgd = new ArrayList<>();
    pnlGiaodich gd;
    /**
     * Creates new form FrmThemXe
     */
    public FrmGiaodich(pnlGiaodich gd) {
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
        this.gd = gd;
       this.listgd = gd.listgd;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSongaym = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNgaymuon = new com.toedter.calendar.JDateChooser();
        dateNgaytra = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtLoaiPP = new javax.swing.JTextField();
        txtPP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTongtien = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        butTinhtien = new javax.swing.JButton();
        butTraxe = new javax.swing.JButton();
        labelMaGD = new javax.swing.JLabel();
        labelMaxe = new javax.swing.JLabel();
        labelMakh = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        butInhoadon = new javax.swing.JButton();
        labeGiam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUẢN LÝ THUÊ XE");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_car_rental_64px.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ GIAO DỊCH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_handshake_32px_1.png"))); // NOI18N
        jLabel2.setText("Mã Giao Dịch");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_driving_guidelines_32px.png"))); // NOI18N
        jLabel8.setText("Mã Xe");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_contact_details_32px.png"))); // NOI18N
        jLabel9.setText("Mã Khách Hàng");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_report_card_32px.png"))); // NOI18N
        jLabel10.setText("Số Ngày Mượn");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_leave_32px.png"))); // NOI18N
        jLabel11.setText("Ngày Mượn");

        txtNgaymuon.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_edit_calendar_32px.png"))); // NOI18N
        jLabel12.setText("Ngày Trả");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_car_service_32px.png"))); // NOI18N
        jLabel13.setText("Loại Phụ Phí");

        txtLoaiPP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLoaiPP.setText("khong co");

        txtPP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPP.setText("0");
        txtPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPPActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_money_32px_1.png"))); // NOI18N
        jLabel14.setText("Phụ Phí");

        txtTongtien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_stack_of_money_32px.png"))); // NOI18N
        jLabel15.setText("Tổng Tiền");

        butTinhtien.setBackground(new java.awt.Color(0, 51, 51));
        butTinhtien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butTinhtien.setForeground(new java.awt.Color(255, 255, 255));
        butTinhtien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cash_in_hand_32px.png"))); // NOI18N
        butTinhtien.setText("Thành Tiền");
        butTinhtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTinhtienActionPerformed(evt);
            }
        });

        butTraxe.setBackground(new java.awt.Color(0, 51, 51));
        butTraxe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butTraxe.setForeground(new java.awt.Color(255, 255, 255));
        butTraxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_car_rental_32px_3.png"))); // NOI18N
        butTraxe.setText("Trả Xe");
        butTraxe.setEnabled(false);
        butTraxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTraxeActionPerformed(evt);
            }
        });

        labelMaGD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        labelMaxe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        labelMakh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        butInhoadon.setBackground(new java.awt.Color(255, 255, 255));
        butInhoadon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butInhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_print_32px.png"))); // NOI18N
        butInhoadon.setText("In Hóa Đơn");
        butInhoadon.setEnabled(false);
        butInhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInhoadonActionPerformed(evt);
            }
        });

        labeGiam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labeGiam.setText("Giảm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLoaiPP, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPP, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(butTinhtien)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butTraxe, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butInhoadon))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSongaym, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labeGiam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(53, 53, 53)
                                .addComponent(txtTongtien)))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgaymuon, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelMaGD, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(labelMaxe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelMakh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(dateNgaytra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMaGD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMaxe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMakh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(txtNgaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateNgaytra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtLoaiPP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butTinhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSongaym)
                    .addComponent(labeGiam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butTraxe, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(butInhoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butTinhtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTinhtienActionPerformed
if(dateNgaytra.getDate() == null){
    JOptionPane.showMessageDialog(this, "CHỌN NGÀY TRẢ");
}
else
{
long a = txtNgaymuon.getDate().getTime();
long b = dateNgaytra.getDate().getTime();
long c = b - a;
if(c <= 0){
    JOptionPane.showMessageDialog(this, "NGÀY TRẢ KHÔNG HỢP LỆ");
}
else{
long e = c/(1000L*60L*60L*24L);
int day = (int)e;
String Songaymuon = String.valueOf(day);
txtSongaym.setText(Songaymuon);
if(day >= 1 && day <= 2){
    labeGiam.setText("0");
}
if(day >= 3 && day <= 7){
    labeGiam.setText("GIẢM 3 %");
}
if(day >= 8 && day <= 14){
    labeGiam.setText("GIẢM 7 %");
}
if(day >= 15 && day <= 22){
    labeGiam.setText("GIẢM 12 %");
}
if(day >= 23){
    labeGiam.setText("GIẢM 15 %");
}
XeDAO dao = new XeDAO();
XeDTO dto = dao.readGiathue(labelMaxe.getText());
GiaoDichDAO dao1 = new GiaoDichDAO();
int khuyenmai = dao1.TinhTien(dto.getGiathue(), day);
int pp = Integer.parseInt(txtPP.getText());
int tong = khuyenmai + pp;
String tong1 = String.valueOf(tong);
txtTongtien.setText(tong1);
butTraxe.setEnabled(true);
butInhoadon.setEnabled(true);
}
}
    }//GEN-LAST:event_butTinhtienActionPerformed

    private void txtPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPPActionPerformed

    private void butTraxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTraxeActionPerformed
if(validata().length()>0){
    JOptionPane.showMessageDialog(this, validata());
}
else{
    java.util.Date d = txtNgaymuon.getDate();
    java.sql.Date ngaymuon = new Date(d.getTime());
    java.util.Date d1 = dateNgaytra.getDate();
    java.sql.Date ngaytra = new Date(d1.getTime());
    int songaymuon = Integer.parseInt(txtSongaym.getText());
    int pp = Integer.parseInt(txtPP.getText());
    int tong = Integer.parseInt(txtTongtien.getText());
    GiaoDichDTO dto = new GiaoDichDTO(labelMaGD.getText(), labelMakh.getText(), labelMaxe.getText()
, songaymuon, ngaymuon, ngaytra, txtLoaiPP.getText(), pp, tong);
    GiaoDichDAO dao = new GiaoDichDAO();
    if(dao.Traxe(dto)){
int index = gd.tableGD.getSelectedRow();
gd.listgd.remove(index);
gd.row.remove(index);
gd.tableGD.updateUI();
JOptionPane.showMessageDialog(this, "GIAO DỊCH THÀNH CÔNG");
XeDAO dao1 = new XeDAO();
        try {
            dao1.Trong(labelMaxe.getText());
        } catch (SQLException ex) {
            Logger.getLogger(FrmGiaodich.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }
}   
    }//GEN-LAST:event_butTraxeActionPerformed

    private void butInhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInhoadonActionPerformed
KhachHangDAO daokh = new KhachHangDAO();
KhachHangDTO dtokh = daokh.readByMotkh(labelMakh.getText());
XeDAO daoxe = new XeDAO();
XeDTO dtoxe = daoxe.readBymotxe(labelMaxe.getText());
Frmhoadon frmhd = new Frmhoadon(this);
frmhd.labeTenkh.setText(dtokh.getTenkh());
frmhd.labeDiachi.setText(dtokh.getDiachi());
frmhd.labeSDT.setText(dtokh.getSdt());
frmhd.LabeTenXE.setText(dtoxe.getTenXe());
frmhd.LabeBienso.setText(dtoxe.getBienSo());
String giathue = String.valueOf(dtoxe.getGiathue());
frmhd.labeGiathue.setText(giathue + "\t VND");
java.sql.Date datengaymuon = new Date(txtNgaymuon.getDate().getTime());
java.sql.Date datengaytra = new Date(dateNgaytra.getDate().getTime());
frmhd.labeNgayMuon.setText(datengaymuon.toString());
frmhd.labeNgayTra.setText(datengaytra.toString());
frmhd.labeSongaymuon.setText(txtSongaym.getText());
int sngaythue = Integer.parseInt(txtSongaym.getText());
frmhd.LabeGiam.setText(labeGiam.getText());
GiaoDichDAO daogd = new GiaoDichDAO();
int tonggiathue = daogd.TinhTien(dtoxe.getGiathue(), sngaythue);
String Tonggiathue = String.valueOf(tonggiathue);
frmhd.labeTongGiaThue.setText(Tonggiathue + "\t VND");
frmhd.labeLoaiPP.setText(txtLoaiPP.getText());
frmhd.labePP.setText(txtPP.getText()+ "\t VND");
frmhd.labeTong.setText(txtTongtien.getText()+ "\t VND");
frmhd.labeNgaytao.setText(datengaytra.toString());
frmhd.setVisible(true);
    }//GEN-LAST:event_butInhoadonActionPerformed
String validata (){
String mess = "";
if(txtSongaym.getText().equals("")){
    mess += "NHẬP SỐ NGÀY MƯỢN \n";
}
if(dateNgaytra.getDate()== null){
    mess += "NHẬP NGÀY TRẢ \n";
}
if(txtLoaiPP.getText().equals("")){
    mess += "NHẬP LOẠI PHỤ PHÍ \n";
}
if(txtPP.getText().equals("")){
    mess += "NHẬP PHỤ PHÍ";
}
if(txtTongtien.getText().equals("")){
    mess += "NHẬP TỔNG TIỀN";
}
return mess;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butInhoadon;
    public static javax.swing.JButton butTinhtien;
    public static javax.swing.JButton butTraxe;
    public static com.toedter.calendar.JDateChooser dateNgaytra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labeGiam;
    public static javax.swing.JLabel labelMaGD;
    public static javax.swing.JLabel labelMakh;
    public static javax.swing.JLabel labelMaxe;
    public static javax.swing.JTextField txtLoaiPP;
    public static com.toedter.calendar.JDateChooser txtNgaymuon;
    public static javax.swing.JTextField txtPP;
    private javax.swing.JTextField txtSongaym;
    public static javax.swing.JTextField txtTongtien;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_traffic_jam_80px_1.png")));
    }
}
