/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import javax.swing.JOptionPane;
import dao.XeDAO;
import dto.XeDTO;

import static gui.pnlXe.tableXe;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Admin
 */
public class FrmThemXe extends javax.swing.JFrame {
    /**
     * Creates new form FrmThemXe
     */
    DefaultTableModel model = null;
    pnlXe xe;
    ArrayList<XeDTO> listxe = new ArrayList<>();
    XeDAO xedao = new XeDAO();
    public FrmThemXe(pnlXe xe) {
        initComponents();
        setIcon();
        this.xe = xe;
        this.listxe = xe.listxe;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaxe = new javax.swing.JTextField();
        txtTenxe = new javax.swing.JTextField();
        txtBienso = new javax.swing.JTextField();
        txtGiathuexe = new javax.swing.JTextField();
        cbLoaixe = new javax.swing.JComboBox();
        cbTrangthai = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        butTaoxe = new javax.swing.JButton();
        butUpdatexe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUẢN LÝ THUÊ XE");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_driving_guidelines_64px.png"))); // NOI18N
        jLabel1.setText("Quản lý xe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_driving_guidelines_32px.png"))); // NOI18N
        jLabel2.setText("Mã Xe");

        txtMaxe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtTenxe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtBienso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtGiathuexe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        cbLoaixe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbLoaixe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "xe tay ga", "xe so", "xe tay con" }));

        cbTrangthai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbTrangthai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "trong" }));
        cbTrangthai.setEnabled(false);
        cbTrangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTrangthaiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_car_insurance_32px_3.png"))); // NOI18N
        jLabel3.setText("Tên Xe");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_card_verification_value_32px_2.png"))); // NOI18N
        jLabel4.setText("Biển Số");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_public_transportation_32px.png"))); // NOI18N
        jLabel5.setText("Loại XE");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_scorecard_32px.png"))); // NOI18N
        jLabel6.setText("Trạng Thái");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_money_32px_1.png"))); // NOI18N
        jLabel7.setText("Giá Thuê");

        butTaoxe.setBackground(new java.awt.Color(0, 51, 51));
        butTaoxe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butTaoxe.setForeground(new java.awt.Color(255, 255, 255));
        butTaoxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_plus_32px_1.png"))); // NOI18N
        butTaoxe.setText("Tạo");
        butTaoxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTaoxeActionPerformed(evt);
            }
        });

        butUpdatexe.setBackground(new java.awt.Color(255, 255, 255));
        butUpdatexe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butUpdatexe.setForeground(new java.awt.Color(0, 51, 51));
        butUpdatexe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_update_left_rotation_32px_6.png"))); // NOI18N
        butUpdatexe.setText("Thay Đổi");
        butUpdatexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdatexeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butTaoxe, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butUpdatexe))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTrangthai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaxe)
                            .addComponent(txtTenxe)
                            .addComponent(cbLoaixe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGiathuexe, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBienso, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMaxe, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txtTenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txtBienso, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbLoaixe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbTrangthai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGiathuexe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butTaoxe, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butUpdatexe, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butTaoxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTaoxeActionPerformed
        validata();
        if(validata().length() > 0 ){
        JOptionPane.showConfirmDialog(this, validata(), "LỖI", JOptionPane.YES_NO_OPTION);
        }
        else{
        int giathue = Integer.parseInt(txtGiathuexe.getText());
         xedao = new XeDAO();
        XeDTO xedto = new XeDTO(txtMaxe.getText(), txtTenxe.getText(), txtBienso.getText()
        , cbLoaixe.getSelectedItem().toString(), cbTrangthai.getSelectedItem().toString(),giathue);
        if(xedao.create(xedto)){ 
            listxe.add(xedto);
             Vector v = new Vector();
                v.add(xedto.getMaXe());
                v.add(xedto.getTenXe());
                v.add(xedto.getBienSo());
                v.add(xedto.getLoaiXe());
                v.add(xedto.getTrangthai());
                v.add(xedto.getGiathue());
                xe.row.add(v);
                model = new DefaultTableModel(xe.row, xe.col);
                xe.tableXe.setModel(model);
                xe.tableXe.updateUI();
                xe.tableXe.getColumnModel().getColumn(1).setPreferredWidth(200);
        xe.tableXe.getColumnModel().getColumn(0).setPreferredWidth(20);
            xe.resetP();
            xe.tabSoluong.updateUI();
        JOptionPane.showMessageDialog(this, "TẠO THÀNH CÔNG");
        }
        else{
        JOptionPane.showMessageDialog(this, "XE ĐÃ TỒN TẠI \n HẢY KIỂM TRA LẠI BIỂN SỐ VÀ MÃ XE");
        }
        }
    }//GEN-LAST:event_butTaoxeActionPerformed

    private void cbTrangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTrangthaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTrangthaiActionPerformed

    private void butUpdatexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdatexeActionPerformed
        try {
 xedao = new XeDAO();
int giathue = Integer.parseInt(txtGiathuexe.getText());
XeDTO xedto1 = new XeDTO(txtMaxe.getText(), txtTenxe.getText(), txtBienso.getText()
, cbLoaixe.getSelectedItem().toString(), cbTrangthai.getSelectedItem().toString(), giathue);
if(xedao.update(xedto1)){
  int index = xe.tableXe.getSelectedRow();
   listxe.set(index, xedto1);
  xe.reserttalble();
  xe.tableXe.setRowSelectionInterval(index, index);
   xe.tableXe.updateUI();
   xe.tableXe.getColumnModel().getColumn(1).setPreferredWidth(200);
   xe.tableXe.getColumnModel().getColumn(0).setPreferredWidth(20);
   xe.resetP();
   
xe.tabSoluong.updateUI();
JOptionPane.showMessageDialog(this, "ĐÃ CHỈNH SỬA");
this.dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmThemXe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butUpdatexeActionPerformed
 String validata(){
    String mess = "";
   if (txtMaxe.getText().equals("")){
mess += "KHÔNG BỎ TRỐNG MÃ SỐ \n" ;
   }
   if(txtTenxe.getText().equals("")){
mess += "KHÔNG BỎ TRỐNG TÊN XE \n";
   }
   if(txtBienso.getText().equals("")){
mess += "KHÔNG BỎ TRỐNG BIỂN SỐ \n";
   }
   if(txtGiathuexe.getText().equals("")){
mess += "KHÔNG BỎ TRỐNG GIÁ THUÊ";
   }
   return mess;
}
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton butTaoxe;
    public static javax.swing.JButton butUpdatexe;
    public static javax.swing.JComboBox cbLoaixe;
    public static javax.swing.JComboBox cbTrangthai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtBienso;
    public static javax.swing.JTextField txtGiathuexe;
    public static javax.swing.JTextField txtMaxe;
    public static javax.swing.JTextField txtTenxe;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_traffic_jam_80px_1.png")));
    }
}
