/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.KhachHangDAO;
import dto.KhachHangDTO;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;

/**
 *
 * @author Admin
 */
public class FrmthemKH extends javax.swing.JFrame {

    pnlKhachhang pnlkh;
    ArrayList<KhachHangDTO> listkh = new ArrayList<>();
    DefaultTableModel model = null;

    /**
     * Creates new form NewJFrame
     */
    public FrmthemKH(pnlKhachhang pnlkh) {
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
        this.pnlkh = pnlkh;
        listkh = pnlkh.listkh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butanh = new javax.swing.JButton();
        txtCmnd = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        labhienanhCM = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labhienanhgp = new javax.swing.JLabel();
        butanhgp = new javax.swing.JButton();
        txtAnhgp = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        butTaokhachH = new javax.swing.JButton();
        butUpdateKhachH = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMakh = new javax.swing.JTextField();
        txtTenkh = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUẢN LÝ THUÊ XE");

        butanh.setText("ẢNH CMND");
        butanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butanhActionPerformed(evt);
            }
        });

        txtCmnd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labhienanhCM, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labhienanhCM, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labhienanhgp, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labhienanhgp, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        );

        butanhgp.setText("ẢNH BẰNG LÁI XE");
        butanhgp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butanhgpActionPerformed(evt);
            }
        });

        txtAnhgp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_member_64px.png"))); // NOI18N
        jLabel1.setText("Quản lý khách hàng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        butTaokhachH.setBackground(new java.awt.Color(0, 51, 51));
        butTaokhachH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butTaokhachH.setForeground(new java.awt.Color(255, 255, 255));
        butTaokhachH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_plus_32px_1.png"))); // NOI18N
        butTaokhachH.setText("Tạo");
        butTaokhachH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTaokhachHActionPerformed(evt);
            }
        });

        butUpdateKhachH.setBackground(new java.awt.Color(255, 255, 255));
        butUpdateKhachH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butUpdateKhachH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_update_left_rotation_32px_6.png"))); // NOI18N
        butUpdateKhachH.setText("Thay Đổi");
        butUpdateKhachH.setEnabled(false);
        butUpdateKhachH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdateKhachHActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_identification_documents_32px.png"))); // NOI18N
        jLabel2.setText("Mã Khách Hàng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_contact_details_32px.png"))); // NOI18N
        jLabel3.setText("Tên Khách Hàng");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_treasure_map_32px.png"))); // NOI18N
        jLabel4.setText("Địa Chỉ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_phone_32px.png"))); // NOI18N
        jLabel5.setText("Số Điện Thoại");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Ảnh CMND");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Bằng Lái");

        txtMakh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtTenkh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTenkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenkhActionPerformed(evt);
            }
        });

        txtDiachi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtSdt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(97, 97, 97)
                        .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(157, 157, 157)
                        .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMakh, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butanh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butanhgp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnhgp, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butTaokhachH, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butUpdateKhachH)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butanh)
                    .addComponent(txtCmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butanhgp)
                    .addComponent(txtAnhgp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butTaokhachH, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butUpdateKhachH, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butanhActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String namefile = file.getAbsolutePath();
        txtCmnd.setText(namefile);
        BufferedImage icon = null;

        try {
            icon = ImageIO.read(new File(txtCmnd.getText()));
        } catch (IOException ex) {
            Logger.getLogger(FrmthemKH.class.getName()).log(Level.SEVERE, null, ex);
        }

        Image image = icon.getScaledInstance(labhienanhCM.getWidth(), labhienanhCM.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageicon = new ImageIcon(image);
        labhienanhCM.setIcon(imageicon);
    }//GEN-LAST:event_butanhActionPerformed

    private void butanhgpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butanhgpActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String namefile = file.getAbsolutePath();
        txtAnhgp.setText(namefile);
        BufferedImage icon = null;

        try {
            icon = ImageIO.read(new File(txtAnhgp.getText()));
        } catch (IOException ex) {
            Logger.getLogger(FrmthemKH.class.getName()).log(Level.SEVERE, null, ex);
        }

        Image image = icon.getScaledInstance(labhienanhgp.getWidth(), labhienanhgp.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageicon = new ImageIcon(image);
        labhienanhgp.setIcon(imageicon);
    }//GEN-LAST:event_butanhgpActionPerformed

    private void butTaokhachHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTaokhachHActionPerformed
        validata();
        if (validata().length() > 0) {
            JOptionPane.showMessageDialog(this, validata(), "Lỗi", JOptionPane.OK_OPTION);
        } else {
            KhachHangDAO dao = new KhachHangDAO();
            KhachHangDTO dto = new KhachHangDTO(txtMakh.getText(), txtTenkh.getText(), txtSdt.getText(), txtDiachi.getText(), txtCmnd.getText(), txtAnhgp.getText());
            if (dao.create(dto)) {
                listkh.add(dto);
                Vector v = new Vector();
                v.add(dto.getMakh());
                v.add(dto.getTenkh());
                v.add(dto.getSdt());
                v.add(dto.getDiachi());
                pnlkh.row.add(v);
                model = new DefaultTableModel(pnlkh.row, pnlkh.col);
                pnlkh.TableKH.setModel(model);
                pnlkh.TableKH.updateUI();
                JOptionPane.showMessageDialog(this, "ĐÃ THÊM KHÁCH HÀNG");
                resert();
                pnlKhachhang.TableKH.getColumnModel().getColumn(3).setPreferredWidth(500);
            } else {
                JOptionPane.showMessageDialog(this, "ĐÃ TỒN TẠI KHÁCH HÀNG NÀY \n KIỂM TRA LẠI MÃ KHÁCH HÀNG VÀ SỐ ĐIỆN THOẠI");
            }
        }
    }//GEN-LAST:event_butTaokhachHActionPerformed

    private void butUpdateKhachHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdateKhachHActionPerformed
        int index = pnlkh.TableKH.getSelectedRow();
        KhachHangDAO dao = new KhachHangDAO();
        KhachHangDTO dto = new KhachHangDTO(txtMakh.getText(), txtTenkh.getText(), txtSdt.getText(), txtDiachi.getText(), txtCmnd.getText(), txtAnhgp.getText());
        try {
            if (dao.update(dto)) {
                listkh.set(index, dto);
                pnlkh.ResertTable();
                pnlkh.TableKH.updateUI();
                pnlKhachhang.TableKH.getColumnModel().getColumn(3).setPreferredWidth(500);
                JOptionPane.showMessageDialog(this, "CHỈNH SỬA THÀNH CÔNG");
                BufferedImage icon = null;

        try {
            icon = ImageIO.read(new File(txtCmnd.getText()));
        } catch (IOException ex) {
            Logger.getLogger(FrmthemKH.class.getName()).log(Level.SEVERE, null, ex);
        }

        Image image = icon.getScaledInstance(pnlkh.labelCmnd.getWidth(), pnlkh.labelCmnd.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageicon = new ImageIcon(image);
        pnlkh.labelCmnd.setIcon(imageicon);
        BufferedImage icon1 = null;

        try {
            icon1 = ImageIO.read(new File(txtAnhgp.getText()));
        } catch (IOException ex) {
            Logger.getLogger(FrmthemKH.class.getName()).log(Level.SEVERE, null, ex);
        }

        Image image1 = icon1.getScaledInstance(pnlkh.labelBanglai.getWidth(), pnlkh.labelBanglai.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageicon1 = new ImageIcon(image1);
        pnlkh.labelBanglai.setIcon(imageicon1);
        pnlkh.TableKH.setRowSelectionInterval(index, index);
         this.dispose();
         
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmthemKH.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_butUpdateKhachHActionPerformed

    private void txtTenkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenkhActionPerformed
    void resert() {
        txtMakh.setText("");
        txtTenkh.setText("");
        txtSdt.setText("");
        txtDiachi.setText("");
        txtCmnd.setText("");
        txtAnhgp.setText("");
        labhienanhCM.setIcon(null);
        labhienanhCM.validate();
        labhienanhgp.setIcon(null);
        labhienanhgp.validate();

    }

    String validata() {
        String mess = "";
        if (txtMakh.getText().equals("")) {
            mess += "KHÔNG ĐƯỢC BỎ TRỐNG MÃ KHÁCH HÀNG\n";
        }
        if (txtTenkh.getText().equals("")) {
            mess += "KHÔNG ĐƯỢC BỎ TRỐNG TÊN KHÁCH HÀNG\n ";
        }
        if (txtDiachi.getText().equals("")) {
            mess += "KHÔNG ĐƯỢC BỎ TRỐNG ĐỊA CHỈ\n";
        }
        if (txtSdt.getText().equals("")) {
            mess += "KHÔNG ĐƯỢC BỎ TRỐNG SỐ ĐIỆN THOẠI\n";
        }
        if (txtCmnd.getText().equals("")) {
            mess += "KHÔNG ĐƯỢC BỎ TRỐNG ẢNH CMND\n";
        }
        if (txtAnhgp.getText().equals("")) {
            mess += "KHÔNG ĐƯỢC BỎ TRỐNG ẢNH BẲNG LÁI XE";
        }
        return mess;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmthemKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmthemKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmthemKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmthemKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmthemKH(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton butTaokhachH;
    public static javax.swing.JButton butUpdateKhachH;
    private javax.swing.JButton butanh;
    private javax.swing.JButton butanhgp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel labhienanhCM;
    public static javax.swing.JLabel labhienanhgp;
    public static javax.swing.JTextField txtAnhgp;
    public static javax.swing.JTextField txtCmnd;
    public static javax.swing.JTextField txtDiachi;
    public static javax.swing.JTextField txtMakh;
    public static javax.swing.JTextField txtSdt;
    public static javax.swing.JTextField txtTenkh;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_traffic_jam_80px_1.png")));
    }
}
