/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.GiaoDichDAO;
import dao.KhachHangDAO;
import dao.XeDAO;
import dto.GiaoDichDTO;
import dto.XeDTO;
import java.util.ArrayList;
import dto.KhachHangDTO;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import sun.swing.SwingUtilities2;
/**
 *
 * @author Admin
 */
public class pnlGiaodich extends javax.swing.JPanel {
    ArrayList<GiaoDichDTO> listgd = null;
    Vector col = new Vector();
    Vector row = new Vector();
    DefaultTableModel model = null;
    /**
     * Creates new form FrmKhachhang
     */
    public pnlGiaodich() {
        initComponents();
 ArrayList<KhachHangDTO>list = new ArrayList<>();
 KhachHangDAO dao1 = new KhachHangDAO();
 list = dao1.Makhachhang();
 for(KhachHangDTO dto : list){
     cbMakhachhang.addItem(dto.getMakh());
 }
 
        col = new Vector();
        col.add("Mã Giao Dịch");
        col.add("Mã Khách Hàng");
        col.add("Mã Xe");
        col.add("Số Ngày Mượn");
        col.add("Ngày Mượn");
GiaoDichDAO dao = new GiaoDichDAO();
listgd = dao.ReadbyGD();
listgd = dao.SapxepHetHang(listgd);
Resettable();
tableGD.updateUI();
    }
public void Resettable(){
    row = new Vector();
for(GiaoDichDTO dto : listgd){
    Vector v = new Vector();
    v.add(dto.getMagd());
    v.add(dto.getMakh());
    v.add(dto.getMaxe());
    v.add(dto.getSongaymuon());
    v.add(dto.getNgaymuon());
    row.add(v);
}
model = new DefaultTableModel(row, col);
tableGD.setModel(model);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGD = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        butTraxe = new javax.swing.JButton();
        butXoagiaodich = new javax.swing.JButton();
        butUpdateGiaodich = new javax.swing.JButton();
        paKh = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbLoaixe = new javax.swing.JComboBox();
        cbTenxe = new javax.swing.JComboBox();
        cbMaxe = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        paKh1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        cbMakhachhang = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtMagd = new javax.swing.JTextField();
        paKh2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dateNgaymuon = new com.toedter.calendar.JDateChooser();
        txtSongayMuon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        labGiam = new javax.swing.JLabel();
        cbSapXep = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_car_rental_64px.png"))); // NOI18N
        jLabel1.setText("GIAO DỊCH");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Thông Tin Giao Dịch", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        tableGD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableGD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Giao Dịch", "Mã Khách Hàng", "Mã Xe", "Số Ngày Mượn", "Ngày Trả"
            }
        ));
        tableGD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableGDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableGD);

        jButton10.setBackground(new java.awt.Color(0, 51, 51));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_plus_32px_1.png"))); // NOI18N
        jButton10.setText("Tạo Giao Dịch");
        jButton10.setMaximumSize(new java.awt.Dimension(117, 41));
        jButton10.setMinimumSize(new java.awt.Dimension(117, 41));
        jButton10.setPreferredSize(new java.awt.Dimension(117, 41));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        butTraxe.setBackground(new java.awt.Color(0, 51, 51));
        butTraxe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butTraxe.setForeground(new java.awt.Color(255, 255, 255));
        butTraxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cash_in_hand_32px.png"))); // NOI18N
        butTraxe.setText("Trả xe");
        butTraxe.setMaximumSize(new java.awt.Dimension(117, 41));
        butTraxe.setMinimumSize(new java.awt.Dimension(117, 41));
        butTraxe.setPreferredSize(new java.awt.Dimension(117, 41));
        butTraxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTraxeActionPerformed(evt);
            }
        });

        butXoagiaodich.setBackground(new java.awt.Color(0, 51, 51));
        butXoagiaodich.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butXoagiaodich.setForeground(new java.awt.Color(255, 255, 255));
        butXoagiaodich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_trash_32px_1.png"))); // NOI18N
        butXoagiaodich.setText("Xóa");
        butXoagiaodich.setMaximumSize(new java.awt.Dimension(117, 41));
        butXoagiaodich.setMinimumSize(new java.awt.Dimension(117, 41));
        butXoagiaodich.setPreferredSize(new java.awt.Dimension(117, 41));
        butXoagiaodich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXoagiaodichActionPerformed(evt);
            }
        });

        butUpdateGiaodich.setBackground(new java.awt.Color(0, 51, 51));
        butUpdateGiaodich.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butUpdateGiaodich.setForeground(new java.awt.Color(255, 255, 255));
        butUpdateGiaodich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_update_left_rotation_32px_3.png"))); // NOI18N
        butUpdateGiaodich.setText("Chỉnh Sửa");
        butUpdateGiaodich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdateGiaodichActionPerformed(evt);
            }
        });

        paKh.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "XE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Loại Xe");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Tên XE");

        cbLoaixe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbLoaixe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "xe tay ga", "xe tay con", "xe so" }));
        cbLoaixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaixeActionPerformed(evt);
            }
        });

        cbTenxe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbTenxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTenxeActionPerformed(evt);
            }
        });

        cbMaxe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbMaxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaxeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Mã Xe");

        javax.swing.GroupLayout paKhLayout = new javax.swing.GroupLayout(paKh);
        paKh.setLayout(paKhLayout);
        paKhLayout.setHorizontalGroup(
            paKhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paKhLayout.createSequentialGroup()
                .addGroup(paKhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(paKhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbMaxe, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTenxe, 0, 192, Short.MAX_VALUE)
                    .addComponent(cbLoaixe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        paKhLayout.setVerticalGroup(
            paKhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paKhLayout.createSequentialGroup()
                .addGroup(paKhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbLoaixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paKhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTenxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paKhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMaxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paKh1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "KHÁCH HÀNG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Số Điện Thoại");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Mã Khách Hàng");

        txtSdt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSdtActionPerformed(evt);
            }
        });

        cbMakhachhang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbMakhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMakhachhangActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Mã Giao Dịch");

        txtMagd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout paKh1Layout = new javax.swing.GroupLayout(paKh1);
        paKh1.setLayout(paKh1Layout);
        paKh1Layout.setHorizontalGroup(
            paKh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paKh1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtSdt)
                .addContainerGap())
            .addGroup(paKh1Layout.createSequentialGroup()
                .addGroup(paKh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paKh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMagd)
                    .addGroup(paKh1Layout.createSequentialGroup()
                        .addComponent(cbMakhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(60, Short.MAX_VALUE))))
        );
        paKh1Layout.setVerticalGroup(
            paKh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paKh1Layout.createSequentialGroup()
                .addGroup(paKh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paKh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbMakhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paKh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtMagd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paKh2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NGÀY MƯỢN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Ngày Mượn");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Số Ngày Mượn");

        txtSongayMuon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSongayMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSongayMuonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Tổng Số Tiền");

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        labGiam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labGiam.setText("giảm");

        javax.swing.GroupLayout paKh2Layout = new javax.swing.GroupLayout(paKh2);
        paKh2.setLayout(paKh2Layout);
        paKh2Layout.setHorizontalGroup(
            paKh2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paKh2Layout.createSequentialGroup()
                .addGroup(paKh2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paKh2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateNgaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paKh2Layout.createSequentialGroup()
                        .addGroup(paKh2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSongayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labGiam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        paKh2Layout.setVerticalGroup(
            paKh2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paKh2Layout.createSequentialGroup()
                .addGroup(paKh2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateNgaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paKh2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSongayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paKh2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        cbSapXep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbSapXep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Giao Dịch Gần nhất", "Giao Dịch Sắp Hết Hạn" }));
        cbSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSapXepActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_sort_32px.png"))); // NOI18N
        jLabel12.setText("Sắp Xếp");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_more_32px.png"))); // NOI18N
        jLabel2.setText("Mã Khách Hàng");

        txttimkiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 402, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butTraxe, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butXoagiaodich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butUpdateGiaodich)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paKh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paKh2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(paKh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paKh2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paKh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSapXep)
                            .addComponent(jLabel12))
                        .addGap(6, 6, 6))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butXoagiaodich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butTraxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butUpdateGiaodich)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
public String Validata(){
String mess = "";
if(txtMagd.getText().equals("")){
 mess += "NHẬP MÃ GIAO DỊCH \n";   
}
if(cbMakhachhang.getSelectedIndex()== -1 ){
 mess += "CHƯA CÓ KHÁCH HÀNG \n";
}
if(cbMaxe.getSelectedIndex()== -1){
mess += "CHỌN XE \n";
}
if(txtSongayMuon.getText().equals("")){
    mess += "NHẬP SỐ NGÀY MƯỢN \n";
}
if(dateNgaymuon.getDate() == null){
    mess += "NHẬP NGÀY MƯỢN";
}
return mess;
}

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
if(Validata().length() > 0){
JOptionPane.showMessageDialog(this, Validata());
}
else{
XeDAO dao2 = new XeDAO();
if(dao2.Sosanh(cbMaxe.getSelectedItem().toString())){
GiaoDichDAO dao = new GiaoDichDAO();
java.util.Date d = dateNgaymuon.getDate();
java.sql.Date ngayMuon = new Date(d.getTime());
int soNgayThue = Integer.parseInt(txtSongayMuon.getText());
GiaoDichDTO dto = new GiaoDichDTO(txtMagd.getText(), cbMakhachhang.getSelectedItem().toString()
, cbMaxe.getSelectedItem().toString(), soNgayThue, ngayMuon);
if(dao.CreateGD(dto)){
XeDAO dao1 = new XeDAO();
try {
        dao1.Thue(cbMaxe.getSelectedItem().toString());
    } catch (SQLException ex) {
        Logger.getLogger(pnlGiaodich.class.getName()).log(Level.SEVERE, null, ex);
    }
JOptionPane.showMessageDialog(this, "GIAO DỊCH THÀNH CÔNG");
listgd.add(dto);
Resettable();
tableGD.updateUI();
delete();
}
else{
    JOptionPane.showMessageDialog(this, "ĐÃ TỒN TẠI GIAO DỊCH NÀY \n KIỂM TRA LẠI MÃ KHÁCH HÀNG, MÃ XE, MÃ GIAO DỊCH");
}
}
else{
    JOptionPane.showMessageDialog(this, "XE ĐANG ĐƯỢC THUÊ");
}
}
    }//GEN-LAST:event_jButton10ActionPerformed

    private void butTraxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTraxeActionPerformed
int index = tableGD.getSelectedRow();
if(index == -1){
    JOptionPane.showMessageDialog(this, "CHỌN GIAO DỊCH");
}
else{
   GiaoDichDTO dto = listgd.get(index);
        FrmGiaodich frmgiaodich = new FrmGiaodich(this);
        frmgiaodich.labelMaGD.setText(dto.getMagd());
        frmgiaodich.labelMakh.setText(dto.getMakh());
        frmgiaodich.labelMaxe.setText(dto.getMaxe());
        frmgiaodich.txtNgaymuon.setDate(dto.getNgaymuon());
        frmgiaodich.setVisible(true);
}
    }//GEN-LAST:event_butTraxeActionPerformed

    private void butUpdateGiaodichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdateGiaodichActionPerformed
int index = tableGD.getSelectedRow();
if(index == -1){
    JOptionPane.showMessageDialog(this, "CHỌN GIAO DỊCH CẦN CHỈNH SỬA");
}
else{
if(JOptionPane.showConfirmDialog(this, "BẠN CÓ CHẮC MUỐN SỬA GIAO DỊCH NÀY "
        , "THÔNG BÁO", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){    
    int songaymuon = Integer.parseInt(txtSongayMuon.getText());
    java.util.Date d = dateNgaymuon.getDate();
    java.sql.Date ngaymuon = new Date(d.getTime());
    GiaoDichDTO dto = new GiaoDichDTO(txtMagd.getText(), cbMakhachhang.getSelectedItem().toString()
, cbMaxe.getSelectedItem().toString(), songaymuon, ngaymuon);
    GiaoDichDAO dao = new GiaoDichDAO();
if(dao.Update(dto)){
GiaoDichDTO dto1 = listgd.get(index);
XeDAO dao1 = new XeDAO();
        try {
            dao1.Trong(dto1.getMaxe());
        } catch (SQLException ex) {
            Logger.getLogger(pnlGiaodich.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            dao1.Thue(cbMaxe.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(pnlGiaodich.class.getName()).log(Level.SEVERE, null, ex);
        }
listgd.set(index, dto);
Resettable();
tableGD.updateUI();
JOptionPane.showMessageDialog(this, "CHỈNH SỬA THÀNH CÔNG");

}
}
}
    }//GEN-LAST:event_butUpdateGiaodichActionPerformed

    private void cbTenxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTenxeActionPerformed
cbMaxe.removeAllItems();
        XeDAO dao = new XeDAO();
        ArrayList<XeDTO> list = new ArrayList<>();
     int index = cbTenxe.getSelectedIndex();
        if(index > -1){
        list = dao.readByTenxeTrong(cbTenxe.getSelectedItem().toString());
        for (XeDTO dto : list) {
cbMaxe.addItem(dto.getMaXe());
        } 
        }
    }//GEN-LAST:event_cbTenxeActionPerformed

    private void cbMaxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaxeActionPerformed

    private void cbMakhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMakhachhangActionPerformed
KhachHangDAO dao = new KhachHangDAO();
KhachHangDTO dto = new KhachHangDTO();
dto = dao.Sdt(cbMakhachhang.getSelectedItem().toString());
txtSdt.setText(dto.getSdt());
    }//GEN-LAST:event_cbMakhachhangActionPerformed

    private void cbLoaixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaixeActionPerformed
       
        cbTenxe.removeAllItems();
        XeDAO dao = new XeDAO();
        ArrayList<XeDTO> list = new ArrayList<>();
        list = dao.readByTenxe(cbLoaixe.getSelectedItem().toString());
        for (XeDTO dto : list) {
            cbTenxe.addItem(dto.getTenXe());
        }

    }//GEN-LAST:event_cbLoaixeActionPerformed

    private void txtSdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSdtActionPerformed
        
        KhachHangDAO dao = new KhachHangDAO();
        ArrayList<KhachHangDTO> list = new ArrayList<>();
        list = dao.ReadBySdt(txtSdt.getText());
        for (KhachHangDTO dto : list) {
            cbMakhachhang.setSelectedItem(dto.getMakh());
        }
    }//GEN-LAST:event_txtSdtActionPerformed

    private void txtSongayMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSongayMuonActionPerformed
XeDAO dao = new XeDAO();
GiaoDichDAO daogd = new GiaoDichDAO();
if(cbMaxe.getSelectedIndex()> -1){
int Ngaythue = Integer.parseInt(txtSongayMuon.getText());
if(Ngaythue >= 1 && Ngaythue <= 30){
XeDTO dto = dao.readMaxe(cbMaxe.getSelectedItem().toString());
int khuyenmai = daogd.TinhTien(dto.getGiathue(), Ngaythue);
String Khuyenmai = String.valueOf(khuyenmai);
jTextField4.setText(Khuyenmai);
if(Ngaythue >= 1 && Ngaythue <= 2){
    labGiam.setText("");
}
if(Ngaythue >= 3 && Ngaythue <= 7){
    labGiam.setText("GIẢM 3 %");
}
if(Ngaythue >= 8 && Ngaythue <= 14){
    labGiam.setText("GIẢM 7 %");
}
if(Ngaythue >= 15 && Ngaythue <= 22){
    labGiam.setText("GIẢM 12 %");
}
if(Ngaythue >= 23 && Ngaythue <= 30){
    labGiam.setText("GIẢM 15 %");
}
}
else{
 JOptionPane.showMessageDialog(this, "NGÀY THUÊ KHÔNG VƯỢT QUÁ 30 NGÀY \n VÀ DƯỚI 1 NGÀY");
}
}
else{
JOptionPane.showMessageDialog(this, "CHỌN MÃ XE");
}
    }//GEN-LAST:event_txtSongayMuonActionPerformed

    private void butXoagiaodichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXoagiaodichActionPerformed
int index = tableGD.getSelectedRow();
if(index == -1){
    JOptionPane.showMessageDialog(this, "CHỌN GIAO DỊCH CẦN XÓA");
}
else{
    if(JOptionPane.showConfirmDialog(this, "BÁN MUỐN XÓA GIAO DỊCH", "XÓA", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
    GiaoDichDTO dto = listgd.get(index);
    listgd.remove(index);
    GiaoDichDAO dao = new GiaoDichDAO();
    if(dao.delete(dto)){
row.remove(index);
tableGD.updateUI();
XeDAO dao1 = new XeDAO();
        try {
            dao1.Trong(dto.getMaxe());
        } catch (SQLException ex) {
            Logger.getLogger(pnlGiaodich.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "XÓA THÀNH CÔNG");
        delete();
    }
}
}
    }//GEN-LAST:event_butXoagiaodichActionPerformed

    private void tableGDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGDMouseClicked
cbMaxe.removeAllItems();
int index = tableGD.getSelectedRow();
GiaoDichDTO dto = listgd.get(index);
cbMaxe.addItem(dto.getMaxe());
cbMakhachhang.setSelectedItem(dto.getMakh());
String songaymuon = String.valueOf(dto.getSongaymuon());
txtSongayMuon.setText(songaymuon);
txtMagd.setText(dto.getMagd());
dateNgaymuon.setDate(dto.getNgaymuon());
    }//GEN-LAST:event_tableGDMouseClicked

    private void cbSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSapXepActionPerformed
int index = cbSapXep.getSelectedIndex();
GiaoDichDAO dao = new GiaoDichDAO();
if(index == 1 ){
listgd = dao.SapxepHetHang(listgd);
Resettable();
tableGD.updateUI();
}
else if(index == 0){
listgd = dao.SapxepGanNhat(listgd);
Resettable();
tableGD.updateUI();
}
    }//GEN-LAST:event_cbSapXepActionPerformed

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
GiaoDichDAO dao = new GiaoDichDAO();
listgd = dao.ReadbyGDsdt(txttimkiem.getText());
Resettable();
tableGD.updateUI();
if(txttimkiem.getText().equals("")){
listgd = dao.ReadbyGD();
Resettable();
tableGD.updateUI();
}
    }//GEN-LAST:event_txttimkiemActionPerformed
public void delete(){
cbTenxe.removeAllItems();
cbMaxe.removeAllItems();
txtSongayMuon.setText("");
txtMagd.setText("");
dateNgaymuon.setDate(null);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butTraxe;
    private javax.swing.JButton butUpdateGiaodich;
    private javax.swing.JButton butXoagiaodich;
    private javax.swing.JComboBox cbLoaixe;
    private javax.swing.JComboBox cbMakhachhang;
    private javax.swing.JComboBox cbMaxe;
    private javax.swing.JComboBox cbSapXep;
    private javax.swing.JComboBox cbTenxe;
    private com.toedter.calendar.JDateChooser dateNgaymuon;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel labGiam;
    private javax.swing.JPanel paKh;
    private javax.swing.JPanel paKh1;
    private javax.swing.JPanel paKh2;
    public static javax.swing.JTable tableGD;
    private javax.swing.JTextField txtMagd;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSongayMuon;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
