/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.util.ArrayList;
import dao.KhachHangDAO;
import dto.KhachHangDTO;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class pnlKhachhang extends javax.swing.JPanel {
    ArrayList<KhachHangDTO> listkh = null;
    Vector col = null;
    Vector row = null;
    DefaultTableModel model = null;
    
    /**
     * Creates new form FrmKhachhang
     */
    public pnlKhachhang() {
        initComponents();
        TableKH.getColumnModel().getColumn(0).setPreferredWidth(1);
        col = new Vector();
        col.add("Mã Khách Hàng");
        col.add("Tên Khách Hàng");
        col.add("Số Điện Thoại");
        col.add("Địa Chỉ");
        KhachHangDAO dao = new KhachHangDAO();
       listkh = dao.readByAll();
      ResertTable();
       TableKH.updateUI();
    }
public void ResertTable(){
     row = new Vector();
       for (KhachHangDTO dto : listkh){
           Vector v = new Vector();
           v.add(dto.getMakh());
          v.add(dto.getTenkh());
          v.add(dto.getSdt());
           v.add(dto.getDiachi());
           row.add(v);
       }
  model = new DefaultTableModel(row, col);
 TableKH.setModel(model);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelCmnd = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelBanglai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableKH = new javax.swing.JTable();
        butThemKH = new javax.swing.JButton();
        butUpdateKH = new javax.swing.JButton();
        butXoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiemsdt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_member_64px.png"))); // NOI18N
        jLabel1.setText("KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CMND", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCmnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCmnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bằng Lái Xe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBanglai, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBanglai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Thông Tin Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        TableKH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TableKH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TableKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Địa Chỉ", "Số Điện Thoại"
            }
        ));
        TableKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableKH);

        butThemKH.setBackground(new java.awt.Color(0, 51, 51));
        butThemKH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butThemKH.setForeground(new java.awt.Color(255, 255, 255));
        butThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_plus_32px_1.png"))); // NOI18N
        butThemKH.setText("thêm");
        butThemKH.setMaximumSize(new java.awt.Dimension(117, 41));
        butThemKH.setMinimumSize(new java.awt.Dimension(117, 41));
        butThemKH.setPreferredSize(new java.awt.Dimension(117, 41));
        butThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butThemKHActionPerformed(evt);
            }
        });

        butUpdateKH.setBackground(new java.awt.Color(0, 51, 51));
        butUpdateKH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butUpdateKH.setForeground(new java.awt.Color(255, 255, 255));
        butUpdateKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_update_left_rotation_32px_3.png"))); // NOI18N
        butUpdateKH.setText("Sửa");
        butUpdateKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdateKHActionPerformed(evt);
            }
        });

        butXoa.setBackground(new java.awt.Color(0, 51, 51));
        butXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butXoa.setForeground(new java.awt.Color(255, 255, 255));
        butXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_trash_32px_1.png"))); // NOI18N
        butXoa.setText("xóa");
        butXoa.setMaximumSize(new java.awt.Dimension(117, 41));
        butXoa.setMinimumSize(new java.awt.Dimension(117, 41));
        butXoa.setPreferredSize(new java.awt.Dimension(117, 41));
        butXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXoaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_more_32px.png"))); // NOI18N
        jLabel2.setText("Số Điện Thoại");

        txtTimKiemsdt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTimKiemsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemsdtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiemsdt, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiemsdt)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(butThemKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(butXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(butUpdateKH, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butUpdateKH, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butThemKHActionPerformed
FrmthemKH themkh = new FrmthemKH(this);
themkh.setVisible(true);
    }//GEN-LAST:event_butThemKHActionPerformed

    private void butUpdateKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdateKHActionPerformed
int index = TableKH.getSelectedRow();
if(index == -1){
    JOptionPane.showMessageDialog(this, "CHỌN KHÁCH HÀNG");
}
else{
 KhachHangDTO dto = listkh.get(index);
FrmthemKH themkh = new FrmthemKH(this);
themkh.txtMakh.setEnabled(false);
themkh.butUpdateKhachH.setEnabled(true);
themkh.butTaokhachH.setEnabled(false);
themkh.txtMakh.setText(dto.getMakh());
themkh.txtTenkh.setText(dto.getTenkh());
themkh.txtSdt.setText(dto.getSdt());
themkh.txtDiachi.setText(dto.getDiachi());
themkh.txtCmnd.setText(dto.getAnhcm());
themkh.txtAnhgp.setText(dto.getAnhgp());
BufferedImage icon = null;
    try {
        icon = ImageIO.read(new File(dto.getAnhcm()));
    } catch (IOException ex) {
        Logger.getLogger(pnlKhachhang.class.getName()).log(Level.SEVERE, null, ex);
    }
Image image = icon.getScaledInstance(themkh.labhienanhCM.getWidth(), themkh.labhienanhCM.getHeight(), Image.SCALE_SMOOTH);
ImageIcon imageicon = new ImageIcon(image);
themkh.labhienanhCM.setIcon(imageicon);


try {
        icon = ImageIO.read(new File(dto.getAnhgp()));
    } catch (IOException ex) {
        Logger.getLogger(pnlKhachhang.class.getName()).log(Level.SEVERE, null, ex);
    }
Image image1 = icon.getScaledInstance(themkh.labhienanhgp.getWidth(), themkh.labhienanhgp.getHeight(), Image.SCALE_SMOOTH);
ImageIcon imageicon1 = new ImageIcon(image1);
themkh.labhienanhgp.setIcon(imageicon1);
themkh.setVisible(true);
}
    }//GEN-LAST:event_butUpdateKHActionPerformed

    private void txtTimKiemsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemsdtActionPerformed
KhachHangDAO dao = new KhachHangDAO();
listkh = new ArrayList<>();
listkh = dao.ReadBySdt(txtTimKiemsdt.getText());
ResertTable();
TableKH.updateUI();
TableKH.getColumnModel().getColumn(3).setPreferredWidth(500);
if(txtTimKiemsdt.getText().equals("")){
listkh = dao.readByAll();
ResertTable();
TableKH.updateUI();
pnlKhachhang.TableKH.getColumnModel().getColumn(3).setPreferredWidth(500);
}
    }//GEN-LAST:event_txtTimKiemsdtActionPerformed

    private void butXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXoaActionPerformed
int index = TableKH.getSelectedRow();
if(index == -1){
 JOptionPane.showMessageDialog(this, "CHỌN KHÁCH HÀNG");
}
else{
    if(JOptionPane.showConfirmDialog(this, "BẠN MUỐN XÓA KHÁCH HÀNG NÀY", "XÓA", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
    KhachHangDTO dto = listkh.get(index);
    listkh.remove(index);
    KhachHangDAO dao = new KhachHangDAO();
    if(dao.delete(dto)){
    row.remove(index);
    TableKH.updateUI();
    TableKH.getColumnModel().getColumn(3).setPreferredWidth(500);
    labelCmnd.setIcon(null);
    labelBanglai.setIcon(null);
}
}
}
    }//GEN-LAST:event_butXoaActionPerformed

    private void TableKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableKHMouseClicked
int index = TableKH.getSelectedRow();
if(index != -1){
 KhachHangDTO dto = listkh.get(index);
    BufferedImage icon = null;
    try {
        icon = ImageIO.read(new File(dto.getAnhcm()));
    } catch (IOException ex) {
        Logger.getLogger(pnlKhachhang.class.getName()).log(Level.SEVERE, null, ex);
    }
Image image = icon.getScaledInstance(labelCmnd.getWidth(), labelCmnd.getHeight(), Image.SCALE_SMOOTH);
ImageIcon imageicon = new ImageIcon(image);
labelCmnd.setIcon(imageicon);


try {
        icon = ImageIO.read(new File(dto.getAnhgp()));
    } catch (IOException ex) {
        Logger.getLogger(pnlKhachhang.class.getName()).log(Level.SEVERE, null, ex);
    }
Image image1 = icon.getScaledInstance(labelBanglai.getWidth(), labelBanglai.getHeight(), Image.SCALE_SMOOTH);
ImageIcon imageicon1 = new ImageIcon(image1);
labelBanglai.setIcon(imageicon1);
}
    }//GEN-LAST:event_TableKHMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TableKH;
    public static javax.swing.JButton butThemKH;
    private javax.swing.JButton butUpdateKH;
    private javax.swing.JButton butXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel labelBanglai;
    public static javax.swing.JLabel labelCmnd;
    private javax.swing.JTextField txtTimKiemsdt;
    // End of variables declaration//GEN-END:variables
}
