/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import dao.AccountDAO;
import dto.AccountDTO;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class pnlTaikhoan extends javax.swing.JPanel {

    /**
     * Creates new form FrmKhachhang
     */
    public pnlTaikhoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        butDoiMatkhau = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDangnhap = new javax.swing.JTextField();
        txtMk = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNhamatkhau1 = new javax.swing.JPasswordField();
        txtNhatmatkhau2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_verified_account_64px.png"))); // NOI18N
        jLabel1.setText("TÀI KHOẢN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        butDoiMatkhau.setBackground(new java.awt.Color(0, 102, 102));
        butDoiMatkhau.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butDoiMatkhau.setForeground(new java.awt.Color(255, 255, 255));
        butDoiMatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_update_left_rotation_32px_3.png"))); // NOI18N
        butDoiMatkhau.setText("Đổi Mật Khẩu");
        butDoiMatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDoiMatkhauActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_verified_account_32px_1.png"))); // NOI18N
        jLabel3.setText("Tên Đăng Nhập");

        txtDangnhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDangnhapActionPerformed(evt);
            }
        });

        txtMk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMkActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_key_2_32px.png"))); // NOI18N
        jLabel5.setText("Mật Khẩu Mới");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_key_2_32px.png"))); // NOI18N
        jLabel6.setText("Nhập Mật Khẩu");

        txtNhamatkhau1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtNhatmatkhau2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_key_2_32px.png"))); // NOI18N
        jLabel4.setText("Nhập Mật Khẩu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("ĐỔI MẬT KHẨU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(butDoiMatkhau))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNhamatkhau1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNhatmatkhau2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMk)))))
                .addGap(0, 119, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNhamatkhau1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtNhatmatkhau2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(butDoiMatkhau)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDangnhapActionPerformed

    }//GEN-LAST:event_txtDangnhapActionPerformed

    private void butDoiMatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDoiMatkhauActionPerformed
if(validata().length() >0){
    JOptionPane.showMessageDialog(this, validata());
}
else{
AccountDAO dao = new AccountDAO();
            String result = "";
            MessageDigest digest;
            try {
                digest = MessageDigest.getInstance("MD5");
                digest.update(new String(txtMk.getPassword()).getBytes());
                BigInteger bigInteger = new BigInteger(1, digest.digest());
                result = bigInteger.toString(16);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(AccountDAO.class.getName()).log(Level.SEVERE, null, ex);
            }
            AccountDTO acc = new AccountDTO(txtDangnhap.getText(), result);
            if(!dao.isExistAcc(acc))
                JOptionPane.showMessageDialog(this, "MẬT KHẨU HOẶC TÀI KHOẢN KHÔNG ĐÚNG", "KIỂM TRA LẠI", JOptionPane.YES_NO_OPTION);  
            else {
if(! new String(txtNhamatkhau1.getPassword()).equals(new String(txtNhatmatkhau2.getPassword()))){
    JOptionPane.showMessageDialog(this, "MẬT KHẨU KHÔNG TRÙNG KHỚP");
}
else{                 
AccountDTO acc1 = new AccountDTO(txtDangnhap.getText(), new String(txtNhatmatkhau2.getPassword()));
                if (dao.Update(acc1)) {
                    JOptionPane.showMessageDialog(this, "UPDATE THÀNH CÔNG", "ĐÃ THAY ĐỔI", JOptionPane.YES_NO_OPTION);
                    txtDangnhap.setText("");
                    txtMk.setText("");
                    txtNhamatkhau1.setText("");
                    txtNhatmatkhau2.setText("");
                
            }
            }
            }
}
    }//GEN-LAST:event_butDoiMatkhauActionPerformed

    private void txtMkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMkActionPerformed

    public String validata (){
String mess = "";
if(new String(txtNhamatkhau1.getPassword()).equals("")){
    mess += "NHẬP MẬT KHẨU \n";
}
if(new String(txtNhatmatkhau2.getPassword()).equals("")){
    mess += "NHẬP MẬT KHẨU \n";
}
if(txtDangnhap.getText().equals("")){
    mess += "NHẬP TÊN ĐĂNG NHẬP";
}
return mess;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDoiMatkhau;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDangnhap;
    private javax.swing.JPasswordField txtMk;
    private javax.swing.JPasswordField txtNhamatkhau1;
    private javax.swing.JPasswordField txtNhatmatkhau2;
    // End of variables declaration//GEN-END:variables
}
