/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type;
import dto.XeDTO;
import dao.XeDAO;
import java.awt.LayoutManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Admin
 */
public class pnlXe extends javax.swing.JPanel {
    Vector col = null;
    Vector row = null;
    Vector colP = null;
    Vector rowP =null;
    FrmThemXe frmthemxe;
public ArrayList<XeDTO> listxe = null;
    DefaultTableModel model = null;
    /**
     * Creates new form FrmKhachhang
     */
    
    public pnlXe() {
        initComponents(); 
 
        col = new Vector();
        col.add("Mã Xe");
        col.add("Tên Xe");
        col.add("Biển Số");
        col.add("Loại Xe");
        col.add("Trạng Thái");
        col.add("Giá Thuê");
        XeDAO xedao = new XeDAO();
        listxe = xedao.readByAll();
        reserttalble();
        tableXe.updateUI();
colP = new Vector();
colP.add("Trống");
colP.add("Thuê");
colP.add("Bảo Trì");
colP.add("Tổng");
resetP();
tabSoluong.updateUI();
    }
 public void reserttalble(){
        row = new Vector();
        for (XeDTO xedto : listxe){
            Vector v = new Vector();
            v.add(xedto.getMaXe());
            v.add(xedto.getTenXe());
            v.add(xedto.getBienSo());
            v.add(xedto.getLoaiXe());
            v.add(xedto.getTrangthai());
            v.add(xedto.getGiathue());
           row.add(v);
    }
 
  model = new DefaultTableModel(row, col);
 tableXe.setModel(model);    
}
public void resetP(){
    rowP = new Vector();
XeDAO dao = new XeDAO();
Vector v = new Vector();
v.add(dao.Soxetrong());
v.add(dao.Soxethue());
v.add(dao.Soxebaotri());
v.add(dao.Tong());
 rowP.add(v);
 DefaultTableModel modelP = new DefaultTableModel(rowP, colP);
 tabSoluong.setModel(modelP);
}
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Timkiemxe = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        butThem = new javax.swing.JButton();
        butUpdatexe = new javax.swing.JButton();
        butXoaxe = new javax.swing.JButton();
        butBaotri = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableXe = new javax.swing.JTable();
        cbSapxep = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbTimkiem = new javax.swing.JComboBox();
        txtTimkiem = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabSoluong = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_motorcycle_64px.png"))); // NOI18N
        jLabel1.setText("XE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        butThem.setBackground(new java.awt.Color(0, 51, 51));
        butThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butThem.setForeground(new java.awt.Color(255, 255, 255));
        butThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_plus_32px_1.png"))); // NOI18N
        butThem.setText("Thêm");
        butThem.setMaximumSize(new java.awt.Dimension(117, 41));
        butThem.setMinimumSize(new java.awt.Dimension(117, 41));
        butThem.setPreferredSize(new java.awt.Dimension(117, 41));
        butThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butThemActionPerformed(evt);
            }
        });

        butUpdatexe.setBackground(new java.awt.Color(0, 51, 51));
        butUpdatexe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butUpdatexe.setForeground(new java.awt.Color(255, 255, 255));
        butUpdatexe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_update_left_rotation_32px_3.png"))); // NOI18N
        butUpdatexe.setText("Chỉnh Sửa");
        butUpdatexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdatexeActionPerformed(evt);
            }
        });

        butXoaxe.setBackground(new java.awt.Color(0, 51, 51));
        butXoaxe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butXoaxe.setForeground(new java.awt.Color(255, 255, 255));
        butXoaxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_trash_32px_1.png"))); // NOI18N
        butXoaxe.setText("Xóa");
        butXoaxe.setMaximumSize(new java.awt.Dimension(117, 41));
        butXoaxe.setMinimumSize(new java.awt.Dimension(117, 41));
        butXoaxe.setPreferredSize(new java.awt.Dimension(117, 41));
        butXoaxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXoaxeActionPerformed(evt);
            }
        });

        butBaotri.setBackground(new java.awt.Color(0, 51, 51));
        butBaotri.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butBaotri.setForeground(new java.awt.Color(255, 255, 255));
        butBaotri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_car_service_32px_2.png"))); // NOI18N
        butBaotri.setText("Bảo Trì");
        butBaotri.setMaximumSize(new java.awt.Dimension(117, 41));
        butBaotri.setMinimumSize(new java.awt.Dimension(117, 41));
        butBaotri.setPreferredSize(new java.awt.Dimension(117, 41));
        butBaotri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBaotriActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Thông Tin Xe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        tableXe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableXe);

        cbSapxep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbSapxep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Giá Tăng Dần", "Giá Giảm Dần" }));
        cbSapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSapxepActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons1/icons8_sort_32px.png"))); // NOI18N
        jLabel3.setText("Sắp Xếp");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_more_32px.png"))); // NOI18N
        jLabel2.setText("Tìm kiếm");

        cbTimkiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbTimkiem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mã Xe", "Loại Xe", "Trạng Thái" }));

        txtTimkiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tổng Số Xe Theo Trang Thái", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jScrollPane2.setBorder(null);

        tabSoluong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tabSoluong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Trống", "Thuê", "Bảo Trì", "Tổng"
            }
        ));
        jScrollPane2.setViewportView(tabSoluong);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbSapxep, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butThem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butUpdatexe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butXoaxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butBaotri, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbSapxep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butUpdatexe)
                        .addComponent(butXoaxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butBaotri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butThemActionPerformed
        FrmThemXe frmthemxe = new FrmThemXe(this);
        frmthemxe.butUpdatexe.setEnabled(false);
        frmthemxe.setVisible(true);
       
    }//GEN-LAST:event_butThemActionPerformed

    private void butUpdatexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdatexeActionPerformed
        int index = tableXe.getSelectedRow();
        
        if(index != -1){ 
            XeDTO xedto = listxe.get(index);
         if(xedto.getTrangthai().equals("thue")){
JOptionPane.showMessageDialog(this, "XE ĐANG ĐƯỢC THUÊ");
         }
         else{
        FrmThemXe frmthemxe = new FrmThemXe(this);
        frmthemxe.cbLoaixe.setSelectedItem(xedto.getLoaiXe());
        frmthemxe.txtMaxe.setText(xedto.getMaXe());
        frmthemxe.txtMaxe.setEnabled(false);
        frmthemxe.txtTenxe.setText(xedto.getTenXe());
        frmthemxe.txtBienso.setText(xedto.getBienSo());
        String giathue = String.valueOf(xedto.getGiathue());
        frmthemxe.txtGiathuexe.setText(giathue);
        frmthemxe.butTaoxe.setEnabled(false);
        frmthemxe.setVisible(true);
        }
        }
        else
 JOptionPane.showMessageDialog(this, "CHỌN XE");
    
    }//GEN-LAST:event_butUpdatexeActionPerformed

    private void butXoaxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXoaxeActionPerformed
        int index = tableXe.getSelectedRow();
        
        // copy qua mấy cái này 
        // sửa lại thành thêm là đc
        
        if(index != -1){
      XeDTO xedto = listxe.get(index);
        if(!xedto.getTrangthai().equals("thue")){    
        if(JOptionPane.showConfirmDialog(this, "BẠN MUỐN XÓA XE NÀY", "XÓA", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        listxe.remove(index);
        // sửa thành add là đc
        XeDAO xedao = new XeDAO();
        if(xedao.delete(xedto)){
        JOptionPane.showMessageDialog(this, "ĐÃ XÓA XE NÀY");
        row.remove(index);
        // làm theo đây này
        model = new DefaultTableModel(row, col);
        tableXe.setModel(model);
        tableXe.updateUI();
        tableXe.getColumnModel().getColumn(1).setPreferredWidth(200);
tableXe.getColumnModel().getColumn(0).setPreferredWidth(20);
        resetP();
        tabSoluong.updateUI();
        }
        }
        }
        else {
        JOptionPane.showMessageDialog(this, "XE ĐANG ĐƯỢC THUÊ");
        }
        }
        else {
            JOptionPane.showMessageDialog(this, "CHỌN XE");
        }
    }//GEN-LAST:event_butXoaxeActionPerformed

    private void butBaotriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBaotriActionPerformed
        int index = tableXe.getSelectedRow();
        if(index != -1){
        XeDTO dto = listxe.get(index);
        if(!dto.getTrangthai().equals("thue")){
        XeDAO dao = new XeDAO();
        try { 
        if(dao.Baotri(dto)){
        listxe.set(index, dto);
        reserttalble();
        tableXe.updateUI();
        tableXe.getColumnModel().getColumn(1).setPreferredWidth(200);
        tableXe.getColumnModel().getColumn(0).setPreferredWidth(20);
        tableXe.setRowSelectionInterval(index, index);
        resetP();
        tabSoluong.updateUI();
        JOptionPane.showMessageDialog(this, "HÃY MANG XE ĐI BẢO TRÌ");
                } 
        } catch (SQLException ex) {
        Logger.getLogger(pnlXe.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else {
        JOptionPane.showMessageDialog(this, "XE ĐANG ĐƯỢC THUÊ");
        }       
        }
        else {
        JOptionPane.showMessageDialog(this, "CHỌN XE");
        }
    }//GEN-LAST:event_butBaotriActionPerformed

    private void txtTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimkiemActionPerformed
int index = cbTimkiem.getSelectedIndex();
XeDAO dao = new XeDAO();
if(index == 0){
listxe = dao.readByMaxe(txtTimkiem.getText());
reserttalble();
tableXe.updateUI();
tableXe.getColumnModel().getColumn(1).setPreferredWidth(200);
tableXe.getColumnModel().getColumn(0).setPreferredWidth(20);
        }
if(index == 1){
listxe = dao.readByLoaixe(txtTimkiem.getText());
reserttalble();
tableXe.updateUI();
tableXe.getColumnModel().getColumn(1).setPreferredWidth(200);
tableXe.getColumnModel().getColumn(0).setPreferredWidth(20);
}
if(index == 2){
listxe = dao.readByTrangThai(txtTimkiem.getText());
reserttalble();
tableXe.updateUI();
tableXe.getColumnModel().getColumn(1).setPreferredWidth(200);
tableXe.getColumnModel().getColumn(0).setPreferredWidth(20);
}
if(txtTimkiem.getText().equals("")){
  listxe =  dao.readByAll();
  reserttalble();
  tableXe.updateUI();
tableXe.getColumnModel().getColumn(1).setPreferredWidth(200);
tableXe.getColumnModel().getColumn(0).setPreferredWidth(20);
}
    }//GEN-LAST:event_txtTimkiemActionPerformed

    private void cbSapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSapxepActionPerformed
int index = cbSapxep.getSelectedIndex();
XeDAO dao = new XeDAO();
if(index == 0){
listxe = dao.Giatangdan(listxe);
reserttalble();
tableXe.updateUI();
tableXe.getColumnModel().getColumn(1).setPreferredWidth(200);
tableXe.getColumnModel().getColumn(0).setPreferredWidth(20);
}
if(index == 1){
listxe = dao.Giagiamdan(listxe);
reserttalble();
tableXe.updateUI();
tableXe.getColumnModel().getColumn(1).setPreferredWidth(200);
tableXe.getColumnModel().getColumn(0).setPreferredWidth(20);
}
    }//GEN-LAST:event_cbSapxepActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Timkiemxe;
    private javax.swing.JButton butBaotri;
    private javax.swing.JButton butThem;
    private javax.swing.JButton butUpdatexe;
    private javax.swing.JButton butXoaxe;
    private javax.swing.JComboBox cbSapxep;
    private javax.swing.JComboBox cbTimkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tabSoluong;
    public static javax.swing.JTable tableXe;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
